version: '3.8'

services:
  database:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: symfony_docker
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - '4306:3306'
    volumes:
      - ./mysql:/var/lib/mysql

  php:
    image: php:8-fpm
    ports:
      - '9000:9000'
    volumes:
      - .:/var/www
    depends_on:
      - database

  nginx:
    image: nginx:stable-alpine
    ports:
      - '8088:80'
    volumes:
      - .:/var/www
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database

  composer:
    image: composer/composer
    volumes:
      - ./:/app
    command: install